# Generated by Django 5.2.12 on 2026-04-16 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


PLACEHOLDER_DOMAIN = "@placeholder.local"


def normalize_existing_users(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    seen_emails: set[str] = set()

    for user in User.objects.all().order_by("id"):
        changed_fields: list[str] = []

        raw_email = (user.email or "").strip().lower()
        if not raw_email:
            normalized_email = f"user-{user.pk}{PLACEHOLDER_DOMAIN}"
        elif raw_email in seen_emails:
            normalized_email = f"user-{user.pk}{PLACEHOLDER_DOMAIN}"
        else:
            normalized_email = raw_email
            seen_emails.add(raw_email)

        if user.email != normalized_email:
            user.email = normalized_email
            changed_fields.append("email")

        real_name = (getattr(user, "first_name", "") or "").strip()
        if not getattr(user, "real_name", "") and real_name:
            user.real_name = real_name
            changed_fields.append("real_name")

        expected_role = "user"
        if getattr(user, "is_superuser", False):
            expected_role = "super_admin"
        elif getattr(user, "is_staff", False):
            expected_role = "admin"
        if getattr(user, "role", None) != expected_role:
            user.role = expected_role
            changed_fields.append("role")

        if getattr(user, "approve_status", "") not in {
            "pending",
            "approved",
            "rejected",
            "disabled",
        }:
            user.approve_status = "pending"
            changed_fields.append("approve_status")

        created_at = getattr(user, "date_joined", None) or timezone.now()
        if getattr(user, "created_at", None) != created_at:
            user.created_at = created_at
            changed_fields.append("created_at")

        updated_at = getattr(user, "last_login", None) or created_at
        if getattr(user, "updated_at", None) != updated_at:
            user.updated_at = updated_at
            changed_fields.append("updated_at")

        if changed_fields:
            user.save(update_fields=changed_fields)


def cleanup_placeholder_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(email__endswith=PLACEHOLDER_DOMAIN):
        user.email = None
        user.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_ensure_plain_test_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["sort", "id"],
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="user",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="real_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("user", "User"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(normalize_existing_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_type",
            field=models.CharField(
                choices=[("division", "Division"), ("department", "Department")],
                default="department",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="department",
            name="page_path",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="department",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="accounts.department",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="sort",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="approve_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("disabled", "Disabled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.department",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(cleanup_placeholder_emails, migrations.RunPython.noop),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset Token",
                "verbose_name_plural": "Password Reset Tokens",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UserAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("register", "Register"),
                            ("create_user", "Create User"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("reset_password", "Reset Password"),
                            ("change_password", "Change Password"),
                            ("forgot_password", "Forgot Password"),
                            ("update_user", "Update User"),
                            ("enable", "Enable"),
                            ("disable", "Disable"),
                            ("delete_user", "Delete User"),
                        ],
                        max_length=50,
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operated_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Audit Log",
                "verbose_name_plural": "User Audit Logs",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
