# Generated by Django 5.2.12 on 2026-04-04 07:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tool_management_project",
            "0004_alter_tool_category_alter_tool_created_by_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tool",
            options={"ordering": ["-updated_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="toolversion",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.RemoveField(
            model_name="tool",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="owner_department",
        ),
        migrations.AddField(
            model_name="tool",
            name="department",
            field=models.CharField(default="电磁 / 干扰", max_length=100),
        ),
        migrations.AddField(
            model_name="tool",
            name="detail",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tool",
            name="code",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tools_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="tool",
            name="latest_version",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="tool",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tool",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("testing", "Testing"),
                    ("deprecated", "Deprecated"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="tool",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="toolversion",
            name="changelog",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="toolversion",
            name="checksum",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="toolversion",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="toolversion",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tool_versions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="toolversion",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="tools/versions/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="toolversion",
            name="file_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="toolversion",
            name="file_size",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="toolversion",
            name="is_latest",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="toolversion",
            name="release_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="toolversion",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="tool_management_project.tool",
            ),
        ),
        migrations.AlterField(
            model_name="toolversion",
            name="version",
            field=models.CharField(max_length=50),
        ),
    ]
