# Generated by Django 5.2.12 on 2026-04-10 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool_management_project", "0005_alter_tool_options_alter_toolversion_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolUploadSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_id", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "target",
                    models.CharField(
                        choices=[("tool_create", "Tool Create"), ("tool_version", "Tool Version")],
                        default="tool_create",
                        max_length=32,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(default=0)),
                ("chunk_size", models.IntegerField(default=5242880)),
                ("total_chunks", models.IntegerField(default=1)),
                ("uploaded_chunks", models.JSONField(blank=True, default=list)),
                ("uploaded_chunks_count", models.IntegerField(default=0)),
                ("checksum", models.CharField(blank=True, default="", max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("uploading", "Uploading"),
                            ("merging", "Merging"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("temp_dir", models.CharField(blank=True, default="", max_length=500)),
                ("merged_file_path", models.CharField(blank=True, default="", max_length=500)),
                ("error_message", models.TextField(blank=True, default="")),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_sessions",
                        to="tool_management_project.tool",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_upload_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-updated_at", "-id"]},
        ),
    ]
