# Generated by Codex on 2026-04-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool_management_project", "0006_tooluploadsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="tooluploadsession",
            name="bound_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bound_upload_sessions",
                to="tool_management_project.toolversion",
            ),
        ),
    ]
